### ISSUE TITLE
Miners/buras don't update their aims when environment changes

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#62]
It is related to wood gathering. When buras collect wood, they eventually start to go far and far away from the place where they started gathering. However, new woods grow up but they're ignored. From my point of view it seems like gathering logic is the same for wood, stone and gold, but it should differ for wood.

**Comment by Andrettin** [comment]
Having the workers check whether for closer trees when going back to gather is a good idea. I'll have to look into how to implement that, though.

**Comment by KroArtem** [comment]
Well, I think the first time they start chopping they get all places where wood is present and do not update their knowledge. At least it looks like this from my point of view.

**Comment by Andrettin** [comment]
Something like that, yes - harvesters return to the place they last harvested. For the AI, the function which has the workers look for resources only assigns them to one if they are idle.

**Comment by KroArtem** [comment]
As far as I understand, it's action_resource.cpp that should be modified, to be precise: COrder_Resource::StartGathering and this piece of code:

```
if (!goal || goal->IsVisibleAsGoal(*unit.Player) == false) {
		// Find an alternative, but don't look too far.
		this->goalPos.x = -1;
		this->goalPos.y = -1;
		if ((goal = UnitFindResource(unit, unit, 15, this->CurrentResource, unit.Player->AiEnabled))) {
			this->State = SUB_START_RESOURCE;
			this->SetGoal(goal);
		} else {
			this->ClearGoal();
			this->Finished = true;
		}
		return 0;
	}
```

**Comment by Andrettin** [comment]
That part of the code pertains to unit-based resources (rather than tile-based ones), and it fires when the harvester is beginning to harvest, rather than when it is going out of the drop-off point to the resource.

I did manage to find the code for choosing a tile to harvest when going out of a drop-off point though, and to implement the fix to this issue there, so that workers will now look for trees closer than the ones they were harvesting before when going out to harvest wood. So this issue is fixed now :)
https://github.com/Andrettin/Wyrmgus/commit/1983f50f7a7923a9a6f279fe6019874026ad9895
