### ISSUE TITLE
Collecting lumber now works incorrectly

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmgus#66]
After you last changes to lumber collection strategy, there is a nasty bug (found it only now). When miners "finish" one piece of tree, they seem to be looking for the nearest tree to lumber mill/town hall, but if it is unreachable, they just do nothing.

![screenshot from 2016-02-08 20 45 13](https://cloud.githubusercontent.com/assets/1813101/12894037/8e661914-cea5-11e5-93fb-f7932fa18399.png)

[lumberjacks doing nothing.sav.zip](https://github.com/Andrettin/Wyrmgus/files/121968/lumberjacks.doing.nothing.sav.zip)

**Comment by Andrettin** [comment]
Thanks for reporting this :)

The bug wasn't caused by the latest change to lumber collection (since that only affected tree tiles rather than objects like wood piles). The bug was probably just not noticed until now because it requires a very specific placement of the lumber mill, the wood piles and the blocking buildings.

I've implemented a fix to the issue:
https://github.com/Andrettin/Wyrmgus/commit/a5f0c7985e30574fab4103869d1ed76e9585a523

If you load your save game, the miners will get right back to work now.

**Comment by KroArtem** [comment]
Ok, that was hard to detect, indeed.

One question not related to this ticket. Do you have any plans regarding localization? I saw some .po files in translation folder, but they're not used, as far as I understand. Is it worth doing? Do you think about stabilizing story/quests so it'll be a string freeze? Is there any sense translating all these names onto other languages?
These are just my thoughts, no need to answer them all. :)

**Comment by Andrettin** [comment]
There were plans to localize the game in some other languages, but they were abandoned because of the workload required to maintain the localizations (since every time a string is changed the localizations would need to be update); and it would also delay the release of new versions.

It would be pretty nice to have the game translated into other languages, but there are these practical impediments.

**Comment by KroArtem** [comment]
Yeah, that's why I asked about string freeze (and you do update strings a lot). Updating stuff could be more or less automated (like, generating new .po/pot file and loading it to transifex and downloading already done translations into repository), but it won't guarantee that everything is translated/translated correctly. 

It will also bring some problems with fonts. I remember in SuperTuxKart we had some problems with Russian translation, then RTL problems, then Chinese support problem... so I'm ok with English version, the question is whether it is acceptable for you. :)
