### ISSUE TITLE
Dependency toward OAML

### ISSUE THREAD

**Issue by MCMic** [Andrettin/Wyrmgus#97]
Hello,

I’m maintaining ArchLinux package of wyrmsun and try to update it from 1.9.9 to 2.2.1.
The cmake fails with:   No download info given for 'oaml' and its source directory:

oaml is a submodule and thus is not included in the tar.gz of the release.
Does that mean I should package oaml on its own?
If so, does wyrmgus needs oaml 1.0 or the git version?

**Comment by akien-mga** [comment]
You can either package OAML for your distro as a shared library (but I haven't checked if it has a proper soname yet), or generate a tarball with the submodule initialised.

**Comment by akien-mga** [comment]
Or you can do as I did for Mageia, with an additional tarball: http://svnweb.mageia.org/packages/cauldron/wyrmsun/current/SPECS/wyrmsun.spec?view=markup&pathrev=996947

**Comment by Andrettin** [comment]
Using the OAML 1.0 version should be fine (and probably more stable than always using the Git version). Wyrmgus' music code hasn't been modified since before the OAML 1.0, so no new features implemented in the library after version 1.0 are used. And the library's functions used by Wyrmgus haven't been modified in a way to make them incompatible either.

**Comment by MCMic** [comment]
Thanks, I did the same thing as Akien and get oaml 1.0 as a separate archive, seems to work.
